### ISSUE TITLE
Serwery "widmo" przy połączeniu lokalnym WiFi

### ISSUE THREAD

**Issue by smndda** [Lemongrabb/ThousandSchnapsen#2]
Podczas dzisiejszych zajęć zauważyłem że zdarza się że zgłoszenie wyłączenia serwera nie jest czasami odbierane przez klienty w sieci lokalnej i zostają na klientach, nazwę to, serwery "widmo" które już nie istnieją ale pokazują się na liście dalej, próba połączenia z nimi kończy się niepowodzeniem, gdyż jak wiadomo, serwer jest wyłączony mimo że wyświetla się że istnieje.

Według mnie najlepszym rozwiązaniem tego problemu byłoby zastosowanie zwykłego pinga wysyłanego przez klienta do serwera co jakiś interwał aby sprawdzał czy on obecnie żyje i ma się dobrze, jeżeli serwer nie odpowie na żądanie w przeciągu tego interwału to klient usunie go z listy wykrytych serwerów lokalnych (to zdarzenie nazywa się ping timeout i znajdziecie go w użyciu w praktycznie każdej architekturze serwer/klient np. IRC).

**Comment by Cyrkie** [comment]
57a2bd5 Zmniejszenie prawdopodobieństwa wystąpienia serwera widmo
