### ISSUE TITLE
Walory estetyczne

### ISSUE THREAD

**Issue by smndda** [Lemongrabb/ThousandSchnapsen#3]
Przy kliknięciu graj przez Wi-Fi z wyłączonym Wi-Fi otrzymujemy komunikat który jest napisany bardzo brzydko i nieatrakcyjnie gdyż ktoś chyba nie potrafi pisać poprawnie po polsku.

https://cdn.discordapp.com/attachments/384717889900511235/564779852767428613/Screenshot_2019-04-08-13-52-56.png

**Comment by Cyrkie** [comment]
Na chwilę obecną jest to placeholder. Wyglądem i treścią GUI zajmują się deweloperzy C.
