### ISSUE TITLE
Brak obsługi polskich znaków w nazwach serwerów

### ISSUE THREAD

**Issue by smndda** [Lemongrabb/ThousandSchnapsen#4]
Po utworzeniu razem z innym testerem wielu serwerów widmo przy połączeniu internetowym zauważyłem że jest brak obsługi polskich znaków.

https://cdn.discordapp.com/attachments/384717889900511235/564781551058026547/Screenshot_2019-04-08-14-00-02.png

Tekst powinien wyglądać następująco: "wyciągnijcie mnie"

**Comment by Neawin** [comment]
Problem nie zawsze wystepuje, u mnie polskie znaki wyswietlają sie prawidłowo.
https://media.discordapp.net/attachments/564751828311474186/564783704686198794/Screenshot_2019-04-08-14-07-18-356_com.example.thousandschnapsen.png?width=305&height=609

**Comment by smndda** [comment]
Na moim urządzeniu w tym samym momencie tak to wygląda:
https://cdn.discordapp.com/attachments/384717889900511235/564784888629428224/Screenshot_2019-04-08-14-13-15.png

Próbowałem zmiany ustawień języka telefonu na Polski oraz Angielski, nie przyniosło to żadnych zmian.
Serwer o nazwie łłł na moim urządzeniu wyświetla się jako BBB.
